language: cpp
compiler: gcc
os: linux
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - make
script:
    - export CC="g++-5"
    - make -e test
    - ./BUILD/test/stsm
