language: cpp
compiler: gcc
os: linux
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
            - make
env:
    global:
        - CC="gcc-7"
        - CXX="g++-7"

script:
    - make test
    - ./BUILD/test/stsm
