language: cpp
compiler: gcc
os: linux
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - astyle
            - make
            - g++-5
script:
    - export CXX="g++-5"
    - make -e test
    - ./BUILD/test/stsm
